title: 子沉Blog
baseurl: "" # For github pages
description: >- # You can edit footer in _includes/footer.md 
  子沉Blog

google_analytics: # Enter your tracking ID. Not available on IPFS

twitter_cards: off # Not available on IPFS. /assets/logo.png required
twitter_username: 

# 日期格式化
date_format: "%Y/%m/%d-%a"

# 图标URL
icon: "https://zichenstudio.github.io/blog/favicon.ico"

# 背景图片URL
background-url: "https://s2.loli.net/2024/02/27/M1JgfDqGaPdzThF.jpg"
background-source: "Background photo by <a href='https://space.bilibili.com/1740643474'>imoutopia</a> on <a href='https://www.bilibili.com/'>BiliBili</a>"

# CC-BY license
ccby: 'This work is licensed under CC BY 4.0. To view a copy of this license, visit <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">http://creativecommons.org/licenses/by/4.0/</a>'

# CC-BY-NC license
ccbync: 'This work is licensed under CC BY-NC 4.0. To view a copy of this license, visit <a href="http://creativecommons.org/licenses/by-nc/4.0/">http://creativecommons.org/licenses/by-nc/4.0/</a>'

# CC-BY-NC-SA license
ccbyncsa: 'This work is licensed under CC BY-NC-SA 4.0. To view a copy of this license, visit <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">http://creativecommons.org/licenses/by-nc-sa/4.0/</a>'

# R15 tips
r15: '<p style="color: #f00"><strong>本内容可能不适合未满15周岁读者阅读</strong>本内容可能包含暴力、粗口、血腥、恐怖、惊悚、性暗示、药物滥用等内容。若无法保持理智，请不要继续阅读。我们不会对任何人阅读此内容而造成的任何后果负责。</p>'

# Build settings
markdown: kramdown
sass:
  style: compressed

future: BOOL

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - README-ultralight.md
  - LICENSE 
  - LICENSE-ultralight

