title: 子沉Blog
baseurl: "" # For github pages
description: >- # You can edit footer in _includes/footer.md 
  子沉Blog

google_analytics: # Enter your tracking ID. Not available on IPFS

twitter_cards: off # Not available on IPFS. /assets/logo.png required
twitter_username: 

# 日期格式化
date_format: "%Y/%m/%d-%a"

# 图标URL
icon: "https://zichenstudio.github.io/blog/favicon.ico"

# 背景图片URL
background-url: "https://s2.loli.net/2023/11/18/Loy27Fhfgu5iBAV.jpg"
background-source: "Background photo by <a href='https://unsplash.com/@auceinss?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText'>Yuming Zhang</a> on <a href='https://unsplash.com/photos/ck-p536ihvg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText'>Unsplash</a>"

# CC-BY license
ccby: ' This work is licensed under CC BY 4.0. To view a copy of this license, visit <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">http://creativecommons.org/licenses/by/4.0/</a>'

# CC-BY-NC license
ccbync: 'This work is licensed under CC BY-NC 4.0. To view a copy of this license, visit <a href="http://creativecommons.org/licenses/by-nc/4.0/">http://creativecommons.org/licenses/by-nc/4.0/</a>'

# CC-BY-NC-SA license
ccbyncsa: 'This work is licensed under CC BY-NC-SA 4.0. To view a copy of this license, visit <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">http://creativecommons.org/licenses/by-nc-sa/4.0/</a>'

# Build settings
markdown: kramdown
sass:
  style: compressed

future: BOOL

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - README-ultralight.md
  - LICENSE 
  - LICENSE-ultralight

